/**
 * @fileoverview Init command — scaffold traces, sample test, and record config.
 *
 * Creates:
 *   traces/example.expected.json  — sample golden trace
 *   tests/example.vcr.test.ts     — sample Vitest test
 *
 * Usage (CLI):
 *   agent-vcr init [--dir <project-dir>]
 */

import { mkdir, writeFile, access } from 'node:fs/promises'
import { join } from 'node:path'

const GOLDEN_TRACE = JSON.stringify(
  {
    version: 1,
    scenario: 'example_happy_path',
    calls: [
      { name: 'lookup_order', args: { orderId: '123' } },
      { name: 'process_refund', args: { orderId: '123', amountDollars: 10 } },
    ],
  },
  null,
  2,
) + '\n'

const SAMPLE_TEST = `/**
 * Example test — generated by \`agent-vcr init\`.
 * Wire \`executeTool\` to your code and adjust the golden trace as needed.
 */
import { describe, it, expect } from 'vitest'
import {
  ScriptedLlm,
  assistantText,
  assistantWithTools,
  collectToolCalls,
  compareTraces,
  loadTraceFile,
  toolCall,
} from 'agent-vcr'

describe('tool trace (example)', () => {
  it('happy path matches golden trace', async () => {
    // Scripted model turns — no live API in CI
    const llm = new ScriptedLlm([
      assistantWithTools([toolCall('lookup_order', { orderId: '123' }, 'c1')]),
      assistantWithTools([toolCall('process_refund', { orderId: '123', amountDollars: 10 }, 'c2')]),
      assistantText('Done.'),
    ])

    // Your dispatch + scripted LLM
    const recorded = await collectToolCalls({
      system: 'You are a support agent. Always look up an order before processing a refund.',
      user: 'Refund $10 on order 123',
      llm,
      async executeTool(name) {
        // Replace with real handlers or stubs
        if (name === 'lookup_order') return { found: true, orderId: '123' }
        if (name === 'process_refund') return { ok: true }
        throw new Error(\`Unknown tool: \${name}\`)
      },
    })

    // Compare to committed golden trace
    const expected = await loadTraceFile('traces/example.expected.json')
    const result = compareTraces(expected.calls, recorded)
    expect(result).toEqual({ ok: true })
  })

  it('regression: skipped lookup fails trace compare', async () => {
    const badLlm = new ScriptedLlm([
      // Omits lookup_order — expect compareTraces to fail
      assistantWithTools([toolCall('process_refund', { orderId: '123', amountDollars: 10 }, 'c1')]),
      assistantText('Done.'),
    ])

    const recorded = await collectToolCalls({
      system: 'You are a support agent.',
      user: 'Refund $10 on order 123',
      llm: badLlm,
      async executeTool(name) {
        if (name === 'process_refund') return { ok: true }
        throw new Error(\`Unknown tool: \${name}\`)
      },
    })

    const expected = await loadTraceFile('traces/example.expected.json')
    const result = compareTraces(expected.calls, recorded)
    expect(result.ok).toBe(false)
  })
})
`

const RECORD_CONFIG = JSON.stringify(
  {
    $comment: 'agent-vcr record config — run: agent-vcr record --config this-file.json --out traces/example.expected.json',
    system: 'You are a support agent. Always look up an order before processing a refund.',
    user: 'Refund $10 on order 123',
    scenario: 'example_happy_path',
    model: 'gpt-4o-mini',
    tools: [
      {
        name: 'lookup_order',
        description: 'Look up an order by ID to verify it exists.',
        parameters: {
          type: 'object',
          properties: { orderId: { type: 'string', description: 'The order ID' } },
          required: ['orderId'],
        },
      },
      {
        name: 'process_refund',
        description: 'Process a refund for an existing order.',
        parameters: {
          type: 'object',
          properties: {
            orderId: { type: 'string' },
            amountDollars: { type: 'number', description: 'Refund amount in dollars' },
          },
          required: ['orderId', 'amountDollars'],
        },
      },
    ],
    stubs: {
      lookup_order: { found: true, orderId: '123', balanceCents: 1000 },
      process_refund: { ok: true, refundedDollars: 10 },
    },
  },
  null,
  2,
) + '\n'

export type InitOptions = {
  /** Root directory of the project (default: process.cwd()). */
  dir?: string
  /** Skip files that already exist instead of throwing (default: false). */
  skipExisting?: boolean
}

export type InitResult = {
  created: string[]
  skipped: string[]
}

/** Scaffold Agent VCR files in a project directory. */
export async function initProject(options: InitOptions = {}): Promise<InitResult> {
  const root = options.dir ?? process.cwd()
  const created: string[] = []
  const skipped: string[] = []

  const files: Array<{ rel: string; content: string }> = [
    { rel: 'traces/example.expected.json', content: GOLDEN_TRACE },
    { rel: 'tests/example.vcr.test.ts', content: SAMPLE_TEST },
    { rel: 'record.config.json', content: RECORD_CONFIG },
  ]

  // Ensure directories exist
  await mkdir(join(root, 'traces'), { recursive: true })
  await mkdir(join(root, 'tests'), { recursive: true })

  for (const f of files) {
    const fullPath = join(root, f.rel)
    const exists = await fileExists(fullPath)
    if (exists) {
      if (options.skipExisting) {
        skipped.push(f.rel)
        continue
      }
      throw new Error(`init: file already exists: ${fullPath}`)
    }
    await writeFile(fullPath, f.content, 'utf8')
    created.push(f.rel)
  }

  return { created, skipped }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}
